# Generated by Django 5.0 on 2024-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('APELLIDO', models.CharField(max_length=100)),
                ('CEDULA', models.CharField(max_length=20, unique=True)),
                ('FOTO', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
