# Generated by Django 5.0 on 2024-02-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='FOTO',
        ),
    ]
