# Generated by Django 5.0 on 2024-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0002_remove_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='FOTO',
            field=models.CharField(default='default/user_default.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
