# Generated by Django 5.0 on 2024-02-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0003_persona_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='FOTO',
        ),
        migrations.AddField(
            model_name='persona',
            name='foto_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
