# Generated by Django 5.0 on 2024-04-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0003_remove_persona_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='photo_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
