# Generated by Django 5.0 on 2024-04-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0004_persona_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='photo_path',
        ),
    ]
