# Generated by Django 5.0 on 2024-04-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0006_persona_foto_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto_path',
        ),
    ]
