# Generated by Django 5.0 on 2024-04-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0010_asistencia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='photo_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
