# Generated by Django 5.0 on 2024-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0011_persona_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconocimientoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
