# Generated by Django 5.0 on 2024-04-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0012_reconocimientofacial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimientofacial',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reconfacial1.persona'),
        ),
    ]
