# Generated by Django 5.0 on 2024-05-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfacial1', '0013_reconocimientofacial_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='person_folder_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
